### ISSUE TITLE
Resources in testing

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/matrix#102]
We would like to be able to include resources in our automated testing.

We want to be able to run tests against local binaries that would be attached to the controller at the time of testing. This way we will be able to verify the correctness of the binaries/resources before we actually upload them to the store.

The need for this has come up during development of the CI for Kubernetes charms. 

Thank you

**Comment by petevg** [comment]
I'd like to deal with this by tapping into conjure-up, and adding the ability for Matrix to run a spell. I'm not 100% certain that this approach will get us everything that we need, but I plan on making a go at it soon (before the end of the month). Will ping this thread when I've got relevant updates.

**Comment by battlemidget** [comment]
Hit me up if you need help

**Comment by petevg** [comment]
PR here: https://github.com/juju-solutions/matrix/pull/107

**Comment by petevg** [comment]
PR Merged!

@ktsakalozos If you pull the latest version of matrix, and you point it at a kubernetes spell that you have checked out locally, matrix should be able to run the deploy, including handling the resources. Does this unblock you from using matrix for testing, or is there more work that we need to do?

**Comment by petevg** [comment]
It looks like @battlemidget is working on testing this ... and is generating bugs that we can use to track progress. I'm going to close this issue out as finished for now :-)
