### ISSUE TITLE
AttributeError: 'Context' object has no attribute 'ha'

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/matrix#108]
I refreshed cwrbox to pick up all kinds of new stuff... One of those things being matrix.  I seem to have hit a most unfortunate error:

http://paste.ubuntu.com/24237456/

On an internet relay chat channel, @petevg said `context.ha` should instead be `context.config.ha`.

**Comment by petevg** [comment]
@kwmonroe @johnsca Fixed here: https://github.com/juju-solutions/matrix/pull/109

**Comment by petevg** [comment]
Thx for the reviews, all. PR merged :-)
