### ISSUE TITLE
matrix not honoring -c <controller>

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/matrix#116]
When matrix fails for whatever reason, I see crashdump fails as well.  As an example, my jenkins log shows matrix being called like this:

```
2017-03-30 00:55:08 DEBUG call ['/usr/local/bin/matrix', '-s', 'raw', '-c', 'aws-w'] (cwd: /tmp/cwr-tmp-azQq_u/bundletester-DmLoVS/spark-processing-dev)
```

Note the `-c aws-w` there.  Now see the failure by expanding `AWS` and clicking the `matrix` link:

http://bigtop.charm.qa/cwr_bundle__bigdata_dev_spark_processing/2/report.html

About 1/3 of the way down, see the crashdump failure:

```
matrix:228:crashdump: Running crash dump
matrix:216:execute_process: ERROR model gce-w:ci-70/job-2-matrix-pet-filly not found
```

This is AWS, yet crash dump is attempting to run on GCE.  It seems matrix is not honoring the `-c <controller>`.

**Comment by petevg** [comment]
I understand what is happening now.

matrix respects the -c flag for the most part. But it isn't passing it into the calls to "juju ssh" and "juju crashdump". So the crashdump fails, even if the rest of the test runs correctly.

Should be able to push a fix soon ...

**Comment by petevg** [comment]
Bleh. This requires fixes both here and in python-libjuju. Wrangling that right now ...

**Comment by petevg** [comment]
PR in python-libjuju: https://github.com/juju/python-libjuju/pull/100

**Comment by petevg** [comment]
PR for python-libjuju closed. PR for matrix here: https://github.com/juju-solutions/matrix/pull/118

**Comment by petevg** [comment]
This is done!
