### ISSUE TITLE
Matrix fails to deploy hadoop-processing

### ISSUE THREAD

**Issue by petevg** [juju-solutions/matrix#15]
I duplicated test_2.matrix, but replaced the wiki-simple bundle with the hadoop-processing bundle.

Matrix fails on the deploy step due to the following error:

`TypeError: addMachines() missing 3 required positional arguments: 'constraints', 'container_type', and 'parent_id'`

Full logs here: http://pastebin.ubuntu.com/23426897/

This might actually be more of an issue w/ python-libjuju, not setting sensible defaults for arguments.

**Comment by petevg** [comment]
Dropping in an update on this one, because I've been doing a lot of work on it.

The error that I ran into is fairly trivial to fix -- a method just needs default arguments.

Unfortunately, there are some deeper issues with the way that python-libjuju passes AddMachinesParams objects to the websocket api. @tvansteenburgh and I have worked through some of them, but matrix still isn't able to get hadoop-processing to deploy.

Am actively working on the issue, and will drop more updates here when/if I've got solutions in hand, or at least a better understanding of the problem.

**Comment by johnsca** [comment]
Can you clarify for me why this only affects `hadoop-processing` and not, e.g., `wiki-simple`?  Does it have to do with the placement directives or constraints?

**Comment by petevg** [comment]
@johnsca It appears to have something to do with the placement directives, which cause us to invoke the AddMachines routine and class, along with the AddMachinesParams class.

**Comment by petevg** [comment]
Update on this: I fixed the bugs in python-libjuju that prevented us from being able to deploy hadoop-processing. (Yay!)

... but I think that I just ran into the connection timeouts mentioned in https://github.com/juju/python-libjuju/issues/7, which means that matrix still won't complete a successful test run (Boo!)

Digging into it now ...

**Comment by petevg** [comment]
PR here: https://github.com/juju-solutions/matrix/pull/34/files
