### ISSUE TITLE
Feature Request: Include capability to collect debug logs 

### ISSUE THREAD

**Issue by arosales** [juju-solutions/matrix#17]
When a failure occurs provide needed debug information so a develper can take action on the failure by diagnosiging the debug logs rather than trying to reproduce.  The testing tool should provide as much insights into the failure as possible that Juju and the charm provides.

One example of a plugin folks created to fill this gap is:
https://github.com/juju/plugins/blob/master/juju-crashdump

**Comment by petevg** [comment]
PRs addressing this here:

https://github.com/juju/plugins/pull/75
https://github.com/juju-solutions/matrix/pull/56

**Comment by petevg** [comment]
This is currently blocked by https://github.com/juju-solutions/matrix/issues/59

We do save off matrix logs, however, which is a start.

**Comment by petevg** [comment]
This is complete, and has been for a while (worked around the ssh bug). Closing this out.
