### ISSUE TITLE
Glitch should only apply changes to apps deployed by the test

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/matrix#24]
While we should generally run matrix tests on clean models, for dev / testing it's often helpful to (re)run against a pre-deployed model.  However, if the current model includes applications that are not part of the matrix test, we might cause mutations to them which are not relevant to the test.

I think glitch should start from `context.apps` instead of `context.juju_model.applications`.

**Comment by petevg** [comment]
I've actually been taking advantage of the fact that matrix will go to town on stuff by deploying things by hand in advance, and then running just the glitch bits of matrix.

That was largely a workaround for when the deploy bits of matrix weren't stable, though. I suppose that need will go away with the actual production version of matrix.

**Comment by petevg** [comment]
@johnsca Aha. Got it. That makes a lot of sense.

**Comment by petevg** [comment]
@johnsca Is this addressed to your satisfaction by https://github.com/juju-solutions/matrix/pull/43?

**Comment by johnsca** [comment]
Yep.
