### ISSUE TITLE
Glitch plan can attempt to operate on removed units

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/matrix#39]
```
glitch:98:glitch: GLITCHING remove_unit: [<Unit entity_id="wiki/0">]
glitch:98:glitch: GLITCHING remove_unit: [<Unit entity_id="mysql/0">]
glitch:98:glitch: GLITCHING add_unit: [<Application entity_id="mysql">]
glitch:98:glitch: GLITCHING reboot: [<Unit entity_id="mysql/0">]
```

It tried to reboot the `mysql/0` unit that was removed by a previous action, and got stuck there (no error, no end).

**Comment by petevg** [comment]
I added some catches for things like this, but I suspect that we're again running into the issue where unit.run can go awol on us.

Maybe we can fix with a timeout?

**Comment by johnsca** [comment]
There is an entirely independent issue with this than the `unit.run()` non-result, since, if the unit has already been removed, it can never have any operations run on it.  Perhaps the checks you mentioned already cover this, but my concerns were:

* Given that the final unit selection happens interleaved with the execution of the actions, it is odd that the units that have been or are being removed are even still possible choices for the subsequent actions.

* Does the plan generation / validation contain checks to ensure that the given set of operations are even possible to execute in that order on the model.   That is, if there is, e.g., one leader and one non-leader unit, can we end up with a plan that includes two `remove_unit` actions with non-leader selectors, since each would independently validate just fine against the initial model, but the second would in actuality be guaranteed to fail for lack of a viable target.

Again, if these concerns have already been addressed by the aforementioned checks, feel free to let me know and close this issue.

**Comment by petevg** [comment]
@johnsca Per our discussion a few weeks ago, I think that we want to stay away from attempting to keep track of what a given plan might do to a model. That's adding more intelligence to the plan generator than I think that we want to add.

It's weird that it is getting a removed unit back from a select. That's either due to our local model being out of date, or python-libjuju keeping unit objects around even when the unit is no longer alive.

**Comment by petevg** [comment]
@johnsca I'm officially beginning work on this one. Currently operating on the theory that the unit isn't getting cleaned up in the model after it is removed.

**Comment by petevg** [comment]
@johnsca Update: I'm wrong. The unit is getting cleaned up. But it can take a little while to get cleaned up. I think that it's probably just an issue of timing (we aren't waiting for the effects of an action to finish before doing the next glitch).

Hmmm ....

**Comment by petevg** [comment]
This partially addresses the issue:

https://github.com/juju-solutions/matrix/pull/42

If we're not seeing exceptions, but are seeing a hang, then I think that the answer is to fix bugs in python-libjuju.

**Comment by johnsca** [comment]
As a drive-by in #43 (because it was preventing me from testing that change reliably), I added a timeout on the glitch code.  I'm not against putting the timeout in libjuju and possibly some pre-validation to fail more gracefully, but at the end of the day, we are asking it to do nonsensical things.

**Comment by petevg** [comment]
Filed https://bugs.launchpad.net/juju-core/+bug/1649637

@johnsca Since we've filed a bug in core, and have a workaround, are you good to close this issue?

**Comment by johnsca** [comment]
Yep.
