### ISSUE TITLE
Quickstart in README doesn't work

### ISSUE THREAD

**Issue by sparkiegeek** [juju-solutions/matrix#46]
The Quick Start currently states:

> `git clone https://github.com/juju-solutions/matrix.git`
> `cd matrix/`
> `tox`
> `. .tox/py35/bin/activate`
> `matrix tests/test_prog`

but that fails hard:

> `usage: matrix [-h] [-c CONTROLLER] [-m MODEL] [-k] [-l LOG_LEVEL]`
> `              [-L [LOG_NAME [LOG_NAME ...]]]`
> `              [-f [LOG_FILTER [LOG_FILTER ...]]] [-s {tui,raw}] [-x FILENAME]`
> `              [-i INTERVAL] [-p PATH] [-D] [-B]`
> `              [-t [TEST_PATTERN [TEST_PATTERN ...]]] [-g GLITCH_PLAN]`
> `              [-n GLITCH_NUM] [-o GLITCH_OUTPUT]`
> `              [additional_suites [additional_suites ...]]`
> `matrix: error: Invalid bundle directory: /home/acollard/Projects/matrix`

It seems like it wants a `bundle.yaml` file in `$PWD`?

**Comment by johnsca** [comment]
This is addressed in #44
