### ISSUE TITLE
Feature request: Snap Matrix

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/matrix#48]
It will almost certainly need to be unconfined, at least for now, but installation and usage would still be easier with a snap.

**Comment by bcsaller** [comment]
I suspect with "home" and "net" it could work today confined so long as the local bundle is under $HOME

**Comment by petevg** [comment]
@lutostag actually put together a snap earlier this month.

I need to follow-up, make sure that it got into the store, and coordinate with updating it with version 0.9.1 once I wrap up that version (hopefully by the end of this week).

**Comment by lutostag** [comment]
@petevg it didn't make it into the store. I was waiting on https://github.com/canonical-ols/build.snapcraft.io/issues/132 but it seems like that will take longer than I had hoped. Will upload the version 0.9.0 later today. And get pushes to edge working. I'll also write up a little howto on releases for us too.

**Comment by johnsca** [comment]
@lutostag Could we work around that by granting you admin on this repo (or on juju-solutions)?

**Comment by lutostag** [comment]
No unfortunately it's the namespace it's in "juju-solutions" not my user iiuc.

**Comment by petevg** [comment]
@lutostag Thank you for the update. Sorry to hear that it's being tricky :-/ Let us know if there's anything we can do to help!

**Comment by lutostag** [comment]
snap install juju-matrix --edge --classic
I believe auto-pushing to edge is working now as well. Will see next time a commit gets pushed to master.

**Comment by petevg** [comment]
@lutostag: it works for me! Thank you :-)

As far as pushes to master go, do we need to be careful about version numbers when merging to master? Will the snap attempt to keep its version in sync with the version in setup.py, or will it keep its own internal version?

**Comment by petevg** [comment]
I'm going to close this issue, since this is done. Thank you @lutostag :-)
