### ISSUE TITLE
Cannot "juju ssh" to machines created in a matrix test

### ISSUE THREAD

**Issue by petevg** [juju-solutions/matrix#59]
To reproduce:

1) Run a matrix test.
2) As the test is running, "juju switch" to the model that the test created.
3) Try to "juju ssh" to one of the machines.

Note that you get a "permission denied (publickey)" error.

Either the path to the public key is not getting set in the terminal env (unlikely, because "juju ssh" to a model that I created works), or we're not copying the juju public key onto the machines that we create in a matrix test (weird, but it is possible that the websocket api is missing the command that creates those keys).

**Comment by johnsca** [comment]
This seems like an issue with libjuju / the API rather than with Matrix.  Can we duplicate this using just libjuju?

**Comment by johnsca** [comment]
Closing this in favor of juju/python-libjuju#42
