### ISSUE TITLE
Investigate using chaos-monkey with glitch for network chaos

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/matrix#72]
The [chaos-monkey](https://github.com/juju/chaos-monkey) repo contains some similar functionality to glitch, but also includes logic for creating network chaos.  We should try to avoid duplication if possible and leverage that code.  This may require some refactoring, though, since Matrix uses libjuju and chaos-monkey was written to be a subordinate.

**Comment by petevg** [comment]
@abentley Is working on this, with the Hammer Time project.

**Comment by abentley** [comment]
I investigated.  I concluded that the unique functionality could not be imported from Chaos Monkey without an invasive rewrite of Chaos Monkey.  Since Chaos Monkey is not in use, a significant rewrite doesn't make sense.  Instead, we can use Chaos Monkey as inspiration and for code snippets.
