### ISSUE TITLE
Add compatibility with Jaas

### ISSUE THREAD

**Issue by petevg** [juju-solutions/matrix#85]
I just started up matrix while juju was pointed at the Jaas controller. It failed pretty spectacularly.

We need to handle the situation where an operator is using Jaas. The best way might be to pass in some Jaas arguments as command line arguments to matrix.

**Comment by battlemidget** [comment]
We need this for conjure-up as well, would having it in libjuju work? We're migrating our code over to that as well

**Comment by petevg** [comment]
@battlemidget libjuju is the right place to put the fix (libjuju might already have support, in which case we just need to call .connect with all the right args.)

**Comment by petevg** [comment]
It looks like the only problem here is that matrix never bothers to specify a cloud. Everything else Just Works in python-libjuju.

Working on a patch right now ...

**Comment by petevg** [comment]
JaaS support mainly automatically works. I have a branch (https://github.com/juju-solutions/matrix/tree/feature/jaas-support) that adds the ability to specific a cloud in matrix, which we need, as the cloud that you're deploying to is ambiguous in JaaS.

Unfortunately, since JaaS is still on Juju 2.0.3 and python-libjuju only supports the latest stable juju 2.1, we are blocked by https://github.com/juju/python-libjuju/issues/49. Without the ability to pick an appropriate facade, we fail with many errors when attempting to connect to the JaaS controller.

**Comment by petevg** [comment]
Here's a sketch of a proposed fix for python-libjuju: http://paste.ubuntu.com/24320954/

Please leave comments on https://github.com/juju/python-libjuju/issues/49

**Comment by petevg** [comment]
I unblocked us in python-libjuju. Now I'm working on the next step, which is to add support for selecting a cloud (and preferably auto-selecting a cloud).

**Comment by petevg** [comment]
PR here: https://github.com/juju-solutions/matrix/pull/127

**Comment by petevg** [comment]
This is done!
