### ISSUE TITLE
Deploy complete before units finished installing

### ISSUE THREAD

**Issue by sparkiegeek** [juju-solutions/matrix#9]
@johnsca demo'd this and it completed the tests whilst the units were still coming up (the charm hadn't even finished install hook)

**Comment by johnsca** [comment]
This was the `tests/rules.1.yaml` case; `tests/test_prog` does block waiting for the health check to determine that the deployment is healthy before starting the other tasks.

We could have the deploy task implicitly block until healthy, but that perhaps limits some of the flexibility, and it also doesn't match the user experience when calling `juju deploy` from the CLI.
