### ISSUE TITLE
No units in model - timeout

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/matrix#92]
I go the following error:
http://pastebin.ubuntu.com/24130907/

How can I assist in figuring this out?

**Comment by petevg** [comment]
Looks like seman might have a repro:

http://juju-ci.vapour.ws/view/CWR/job/cwr-aws/2104/console

**Comment by seman** [comment]
This seems to occur more often:
https://pastebin.canonical.com/184080/
https://pastebin.canonical.com/184082/

**Comment by petevg** [comment]
@seman @ktsakalozos I suspect what is happening here is that python-libjuju is losing the websocket connection, but not telling us about it. Fixing it is going to be interesting. Adding a Pinger might help a bit, but I think that we also need to figure out a sensible "reconnect and resume" routine, and figure out where to stick it.

**Comment by petevg** [comment]
Moved to Beta milestone, as I think that it is important; most of the work is probably going to happen on the python-libjuju side.

**Comment by petevg** [comment]
Opened https://github.com/juju/python-libjuju/issues/99 in python-libjuju.

**Comment by petevg** [comment]
See updates to https://github.com/juju/python-libjuju/issues/99 for some thinking on this ...

**Comment by petevg** [comment]
This should be fixed, as of the merge that I just made.
