### ISSUE TITLE
matrix doesn't use lxd cred in 2.1

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/matrix#93]
Juju 2.1 now requires credentials for lxd.  In cwr-ci, we support this with the `set-credentials` action.  This works for cwr models, but fails when matrix tries to create a model:

```
matrix:124:load_suites: Parsing /usr/local/lib/python3.5/dist-packages/matrix/matrix.yaml
matrix:461:add_model: Creating model matrix-happy-pig
matrix:380:run: Error adding model: no credential specified
------------------------------------------------------------------------------
matrix:431:cleanup: Error while running crashdump.
```

**Comment by petevg** [comment]
Oof. I think that we need to be more specific about our controller connection in matrix. The refactor shouldn't be too bad ...

**Comment by johnsca** [comment]
I think we just need to remove the localhost / lxd exemption in the code to get the credentials from the files.
